apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  ports:
    - name: es01
      nodePort: 30001
      port: 9200
      targetPort: 9200
    - name: es02
      nodePort: 30002
      port: 9300
      targetPort: 9300
    # - name: kibana
    #   nodePort: 30003
    #   port: 5601
    #   targetPort: 5601
  selector:
    app: es
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
spec:
  serviceName: es
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
          tty: true
          stdin: true
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTICSEARCH_PASSWORD
              value: SE2320
            - name: xpack.security.enabled
              value: "false"
        # - name: kibana
        #   image: docker.elastic.co/kibana/kibana:8.3.3
        #   ports:
        #     - containerPort: 5601
        #   volumeMounts:
        #     - mountPath: /usr/share/kibana/config/certs
        #       name: certs
        #     - mountPath: /usr/share/kibana/data
        #       name: kibanadata
        #   env:``
        #     - name: ELASTICSEARCH_USERNAME
        #       value: kibana_system
        #     - name: ELASTICSEARCH_PASSWORD
        #       value: SE2320
      volumes:
        - name: certs
          nfs:
            server: 192.168.0.137
            path: /root/data/main_process/elk/certs
        - name: esdata
          nfs:
            server: 192.168.0.137
            path: /root/data/main_process/elk/es
        # - name: kibanadata
        #   nfs:
        #     server: 192.168.0.137
        #     path: /root/data/main_process/es/kibana
