kind: Deployment
apiVersion: apps/v1
metadata:
  name: main-process
  labels:
    app: back-end
spec:
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end-legacy
          image: east-3.myhuaweicloud.com/zlm/back_end:3
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1900m
              memory: 3800Mi
            requests:
              cpu: 1000m
              memory: 2000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: main-process
spec:
  selector:
    app: back-end
  ports:
    - port: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: main-process
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-process
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
