apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  ports:
    - nodePort: 30000
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: elk
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elk
spec:
  serviceName: elk
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elk
          image: elk:10.8
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
          env:
            - name: elk_ROOT_PASSWORD
              value: SE2320g2abcabc
            - name: elk_USER
              value: g2
            - name: elk_PASSWORD
              value: SE2320
      volumes:
        - name: data
          nfs:
            server: 10.1.142.64
            path: /root/data/main_process/elk
