apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - nodePort: 30000
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.8
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: SE2320g2abcabc
            - name: MARIADB_USER
              value: g2
            - name: MARIADB_PASSWORD
              value: SE2320
      volumes:
        - name: data
          nfs:
            server: 10.1.142.64
            path: /root/data/main_process/mariadb
